resources:
  - name: my_public_fork_git_repo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: elioengcomp/jfrog-pipelines-test
      branches:
        include: {{gitBranch}}
      buildOn:
        commit: true
        pullRequestCreate: true
      cloneProtocol: https

pipelines:
  - name: test_public_fork
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: my_public_fork_git_repo
          integrations:
            - name: my_art
            - name: my_k8s
        execution:
          onExecute:
            - printenv
            - update_commit_status my_public_fork_git_repo --status success --message 'build is done'

      - name: buid_go_project
        type: GoBuild
        configuration:
          inputResources:
            - name: my_public_fork_git_repo
          integrations:
            - name: my_art
            - name: my_k8s
          sourceLocation: resources/go_project
          resolverRepo: test-go
          goCommand: test -v

  - name: test_step_with_integration
    steps:
      - name: build
        type: Bash
        configuration:
          integrations:
            - name: my_github
        execution:
          onExecute:
            - printenv

  - name: test_public_fork_ps
    steps:
      - name: build_ps
        type: PowerShell
        configuration:
          nodePool: win
          inputResources:
            - name: my_public_fork_git_repo
          integrations:
            - name: my_k8s
        execution:
          onExecute:
            - "dir env:"
            - update_commit_status my_public_fork_git_repo -status 'success' -message 'build is done'
